package remover

import (
	"fmt"
	"io"
	"os"
	"regexp"
)

const (
	StandardInput        = "<standard-input>"
	stringValueSeparator = ","
)

type SourceFile struct {
	filePath             string
	codeGeneratedPattern *regexp.Regexp
}

// NewSourceFile constructor
func NewSourceFile(filePath, generatedName string) *SourceFile {
	return &SourceFile{
		filePath: filePath,
		codeGeneratedPattern: regexp.MustCompile(
			fmt.Sprintf(`.*// Code generated .*%s.* DO NOT EDIT\..*`, generatedName),
		),
	}
}

func (f *SourceFile) IsAutoGenerated() (bool, error) {

	var originalContent []byte
	var err error
	if f.filePath == StandardInput {
		originalContent, err = io.ReadAll(os.Stdin)
	} else {
		originalContent, err = os.ReadFile(f.filePath)
	}
	if err != nil {
		return false, err
	}

	return f.isFileAutoGenerate(string(originalContent)), nil
}

func (f *SourceFile) isFileAutoGenerate(c string) bool {
	return f.codeGeneratedPattern.MatchString(c)
}
