package reviser

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io"
	"os"
	"regexp"
)

const (
	StandardInput        = "<standard-input>"
	stringValueSeparator = ","
)

type SourceFile struct {
	filePath             string
	codeGeneratedPattern *regexp.Regexp
}

// NewSourceFile constructor
func NewSourceFile(filePath, generatedName string) *SourceFile {
	return &SourceFile{
		filePath: filePath,
		codeGeneratedPattern: regexp.MustCompile(
			fmt.Sprintf(`^// Code generated .*%s.* DO NOT EDIT\.$`, generatedName),
		),
	}
}

func (f *SourceFile) IsAutoGenerated() (bool, error) {

	var originalContent []byte
	var err error
	if f.filePath == StandardInput {
		originalContent, err = io.ReadAll(os.Stdin)
	} else {
		originalContent, err = os.ReadFile(f.filePath)
	}
	if err != nil {
		return false, err
	}

	fset := token.NewFileSet()

	pf, err := parser.ParseFile(fset, "", originalContent, parser.ParseComments)
	if err != nil {
		return false, err
	}

	return f.isFileAutoGenerate(pf), nil
}

func (f *SourceFile) isFileAutoGenerate(pf *ast.File) bool {
	for _, comment := range pf.Comments {
		for _, c := range comment.List {
			if f.codeGeneratedPattern.MatchString(c.Text) && c.Pos() < pf.Package {
				return true
			}
		}
	}
	return false
}
